### ISSUE TITLE
How to completely delete pending registration account?

### ISSUE THREAD

**Issue by zlaxy** [redmatrix/hubzilla#1086]
Some robot tried to register on my server, this robot didn't pending registration. I remove this account, but there was a footprint left of him:
![2018-04-19-091525_1280x800_scrot](https://user-images.githubusercontent.com/19224533/38975343-2eb554fc-43b6-11e8-8949-1ad121123587.png)
(all of 3 current registered accounts are confirmed)
Also in /admin/channels/ there is only 3 channels now.

How to completely delete pending registration account and all his tracks?

**Comment by git-marijus** [comment]
This was a bug and is already fixed in dev branch. The pending registration count will cleanup itself.

**Comment by zlaxy** [comment]
@git-marijus i updated Hubzilla to 3.4:
![2018-05-04-124916_1280x800_scrot](https://user-images.githubusercontent.com/19224533/39622122-c5158676-4f99-11e8-97c7-f01a2ff4155c.png)
Is this fix not included in the release?
Please indicate me on this commit, i try to clean 'pending registration count' manually.

**Comment by zlaxy** [comment]
@git-marijus 
Switched on dev branch today, it looks that is not fixed:
![2018-05-19-001045_1280x800_scrot](https://user-images.githubusercontent.com/19224533/40258136-405d3652-5af9-11e8-822a-953baa334a95.png)

**Comment by hfroese** [comment]
Same here:

![20180519-0948](https://user-images.githubusercontent.com/1968490/40266341-d2e689c4-5b49-11e8-8a40-385ffe757e64.png)

**Comment by zotlabs** [comment]
I've submitted a patch

**Comment by zlaxy** [comment]
@zotlabs Now fine:
![2018-05-19-113202_1280x800_scrot](https://user-images.githubusercontent.com/19224533/40266674-5f998a20-5b58-11e8-80a9-bb302c3b12e7.png)
Thanks!

**Comment by hfroese** [comment]
Here also. Thanks Mike.
