### ISSUE TITLE
Strip spaces from frendica posts in stream

### ISSUE THREAD

**Issue by zlaxy** [redmatrix/hubzilla#1119]
Orginal post in frendica:
https://f.pztrn.name/display/9afca3c5175ae0fe5962f92030919023
![scrot](https://s7.postimg.cc/ykoqlwx8r/2018-04-26-111602_1280x800_scrot.png)
This post in my network stream:
![scrot](https://s7.postimg.cc/438vudhln/2018-04-26-111611_1280x800_scrot.png)
This is not the first post of this user with that problem.

What could be the reason? How to fix it?

**Comment by git-marijus** [comment]
I don't have an explanation for that. It seems the spaces after commas and dots remain intact?

**Comment by zotlabs** [comment]
I've taken the original text (copied from the Friendica site), and run it through all the format translations which Hubzilla provides on Diaspora posts. 

Original text: Начал замечать, что порноспам добрался до федеративных сетей. Например, к нескольким постам нашел лайки от персонажей, у которых в имени линка на дорвей.

I'll provide the results below. The first is Diaspora/markdown to bbcode (which does two conversion internally; first markdown to HTML and then HTML to bbcode).

1: Начал замечать, что порноспам добрался до федеративных сетей. Например, к нескольким постам нашел лайки от персонажей, у которых в имени линка на дорвей.

The second is converting bbcode from this prior translation and converting it to HTML as we do for display.

2: Начал замечать, что порноспам добрался до федеративных сетей. Например, к нескольким постам нашел лайки от персонажей, у которых в имени линка на дорвей.

As you can see the results are identical.  Assuming we receive the text "intact" in Diaspora markdown, the result should be correct. These are all the transformations that we apply. In order to troubleshoot this further we need to see what Friendica provides "on the wire" after its own conversion processes from bbcode to markdown and see if they are indeed converted intact from that service.

**Comment by zotlabs** [comment]
I've dug a bit further and may have found something amiss in the xml parser.

**Comment by git-marijus** [comment]
I had to revert those changes due to issues with the diaspora plugin.
The resulting array looked like 
```
Array
(
    [author] => xxx@xxx.net
    [guid] => a85d7459155ae6dd5b24361446015594
    [parent_guid] => 39beb0d02e8301368acc101b0e8ace24
    [parent_type] => Post
    [positive] => true
    [author_signature] => ObiouZ7iibFmwFJPzpyr9yrY77GYJ94cq6KpeI2nMvugEq2hXqktkld/Iq20BN9HSTaJm4j9pEb1q0AUSVB117nl4pgA3TJbcD81HxM8abcvMzBRGN59j0lm/FZxlbp2Y/DG0ZP5mE0QkfdIPC7bSGCM1sI+Dpxi8FXjegYR3okCicvH79pl2JtGiXPjRz6KeanS/hcr6zigRLDXKyh9JI3P6RhIX/z1lwMAj0mg+oOwMv4Fjab94sAljtsHXcUsQTWsrHTt6N97SB98idktG884ow5zsxnDdAtW+knpLPBzZGqhW6/FhXG6xtQlrDdeQGFIAhHQS1M65MuJ4/Gk6KAJ/2Pn0GYgr7XGt687eoIEyXghQ/QUgOeHUceUcGhpmMkB3/O6yL11vPfxSniEV6tNMdnqHIAuSjB+ebSiyHRHJDnnoo5Ao+xHOze29Nr2F/IXHJH0SI+XMS/KALt0vQtr0T5GaIDw+zR0xyx5C0CBUUC5OAZ3a5OEUqel90/MOxgLs67IMLnIB8Odl96cXLMbSCClgu2w4A7tI4CxeOArzFkKhOcODc8h0Pkpp+KBGgnEJfkzj06ykT37r2ZSc0CenIHrWCNPtITzcxusMg1ALO7uUgOXVUkR9GXMpAC4FZDTxsnl9sjASB/WIy1BvGBNJYLnQe+iFGriuuqJmLI=
    [parent_author_signature] => P9OLx7B2qXfI7mnIwatrBbeGmlboT6ZbNanbdvPAfWeffnA8V0Q509LUNUh2GKFQmoc1ojDqJ1KEug9+V1tZyBNynX9fLemjB6LZ6SYYjN7jJTcYzn+QOpYHN+x4OQ4i2+wp8fb9aEFDFsXLRwBFAaAvfbAw8x8lv+yQAlm8AjjcGsnq5vpLUf1qTtIhkCwhJ6I3p80HdPZZCNm3RTwwuankzRmJjtQq0PMA9pGryXrCO1LrX3be4ZKGCWpSkqogqQSlfmdExwgRCj8rVJxZXSCvBaslsGfwDzGDesOkWOc86pwJMU74ZhOYGpalHs4pAutrchyiZjMVgfz2sl0DFPSarLUMl/uuoWfvN3tVowLrqLqF3HohCIPsWREWRJ/jMu3iUaTDFKxdNS7/OmjEle21tq+hRDY3C8TCG+N6WAphaZaVq7VY4j8KkegZgMAb1FGNj8bqs9MAOsoKmTkSmoY1adUT8Zn9srLLYVgt63JayZN87jEcoB2I6Vkx5DsPelsXcUXRUvcspQSXqr0/ax6ZnsRE7v5TbloU+wcRGu5tah6X0crHu81MP6bUKkQOJ/KV5p3swnt43JQPuLDsd9sQ4+unKCR9s1YkJcNoHf3qvRQakFMe5zUW9Z9QDNdonLdWnY4eGPoxCj9Qgs4tLBN6cVl5eM9lEJ/MvAe3M0c=
)

```
instead of something like that:

```
Array
(
    [like] => Array
        (
            [author] => xxx@xxx.org
            [guid] => b27f73202e98013641222a0000053625
            [parent_guid] => ef833ca0141c0136cc4d0242ac110006
            [parent_type] => Post
            [positive] => true
            [author_signature] => rvbH3QH909SqCYg7INdlPLcRjpqX737+99w/VGSTsTLWX8oDX1ny0Q1aGrEP/n5LYDWTWSx2h7OeOsIuwd38v6pZPKRF+ESJFwKrZsGVX8jOzWB91sAnmy54i0v3FLS9jiAA+2u0fnh7WjgcLDXjGmQwO6vQagvhsCCiMab2glDwL/hdmm7C+Qlqc37gkFNqbY1ZvErnVv3oHiWRg9RfWqwxHbmLqAgHiFtCP8xfCUbo3Ap/f/0H6HYwsfXLdmU4UjyqEdG7CE0xF6FliNY/kk3sWnckLF9aQgUhfxLHTUur860P6RrHOxJbUoVON5Hye4d7BQmZiU/hih6ASEwmMcYSkRYd5o8hoe6NMl8bxJ2u9ZzMYcsbJJioH5GjWW3ERj2tug8h4phJLtR30zZX8eR50GJBEJ+kbPF6H1PeDrcg/G07Zq9Ci+rVnv9rfsPaesnDbwyr3LalkpiMwBv6/3KledkOdhXuIiVoYLc+qesyzW9/rz49iX3LZZXviJHHLBhlU0SkH0qtVFnPOLKdNe4wjQV6XaidyqjvW9oLXJVDe3030VsYaTPGEd5pVqiFBNmmbkdsr7F9as/68yrui01watGsS8t709+ex0P3uYa1I5Ho4462R1EoDeF6tC2i/YYKlPbP1o+N2ikJRMLCo8GXSx9KbKaarrWA6BusVko=
            [parent_author_signature] => ZdwhRtzIrG21jF1V51KN6j52kjt5Sfqe8X+xdNI9irokzE0UHYuKiSfG1hbHMcGHrJNY0bjWcRV8I9pzUJP7iBIZnQbjAv4/ROCxD0xL6AlthnQ8PxnT4EfhegTX/Q0tBXKJepQfiiTcOw7lhfG7KZZd2u199GiG4ExLxhM3LbX90lvpDj9OegR8AAh/TVS0Qdu408JU0vObzM06gdOYKINIQCg/0WRK6fIEJu9tVCBZuh4KGj8MBdIM7wxfRTaBbGOdsgfqyMa8ueVcj0yzBqQ/d7kY0999MoESFQ+VPWZWGpJcyg9K4JojwFCOhYIfhawbyOII+/jkpX6S9/XNFeeP6gs88yLH17OM2v1YAvsnulbBCUPRhBKW0Mjui7F1yLjiQfA6vKimWlqltSf7wtnn75Wf57B9gDns2HRIQ59eJdi6ibNVI5AyU1B9Nrnb0DPgeOz8N1UiUmnk584Jr7FOPAa8VXqMFoW5trUQrPi1YB4JgDqs4dH7LgSl7NdCLRf+6qd1DJ6qznCz3Cx8RFuz3zXnT9rm9vQxwFkuzXTMPIiFFjXzwzAjBkdEN+Oaxn5kxQ/bdd7Y2hcNSjF2e/4td5x78px1tJmIQXYulodoS2sx2AwcCu8pqJ164LfqmQTKiMShmjOoXUGVeyNeI4nzOotUSAp9LRR/nIv6FQ8=
        )

)

```

**Comment by zlaxy** [comment]
@git-marijus @zotlabs 
It seems that the problem is typical not only for frendica, but for all other cases in alphabets other than Latin:
[https://pod.afox.me/posts/958af3302f430136e4690c010a8a5a01](url)
![scrot](https://s7.postimg.cc/ucfasqlpn/2018-05-01-110151_1280x800_scrot.png)
[https://diasp.org/posts/0ca5fbf02f430136984b047d7b62795e](url)
![scrot](https://s7.postimg.cc/s7uxrncd7/2018-05-01-110139_1280x800_scrot.png)
This is samples of the top ten of my current pubstream.

**Comment by zotlabs** [comment]
We can see the problem now. It's not actually a hubzilla bug, but a bug that's deep in PHP's libxml parser. We're currently trying to find the best way to work around it.

**Comment by git-marijus** [comment]
The work around is now in RC branch. I'll leave this issue open until the root cause will be fixed though.

**Comment by zlaxy** [comment]
@git-marijus @zotlabs 
Thanks, everything looks good in network stream with 3.4:
![2018-05-07-081139_1280x800_scrot](https://user-images.githubusercontent.com/19224533/39686412-836115e4-51d1-11e8-97e8-8950b4f5417f.png)
![2018-05-07-081059_1280x800_scrot](https://user-images.githubusercontent.com/19224533/39686415-872551ea-51d1-11e8-9345-7586227420db.png)

**Comment by zlaxy** [comment]
@git-marijus @zotlabs This problem repeat again (with 3.4), in Diaspora's repost:
https://diasp.org/posts/c82013f0346a013698c5047d7b62795e
![2018-05-08-085152_1280x800_scrot](https://user-images.githubusercontent.com/19224533/39740206-4dcbb746-529d-11e8-986c-fb82059a781b.png)

**Comment by git-marijus** [comment]
I just pushed a fix for the reshare issue to master. Retest please!

**Comment by zlaxy** [comment]
@git-marijus Please point me to a specific commit with this reshare fix - problem still exists after `util/udall` two minutes ago.

**Comment by zlaxy** [comment]
Reposts look fine nowadays:
![2018-05-17-091037_1280x800_scrot](https://user-images.githubusercontent.com/19224533/40159514-50ec8826-59b2-11e8-9214-01284684e211.png)
Thanks!
