### ISSUE TITLE
Misc. issues with new 'insert photo from photo album' [master]

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/hubzilla#475]
1. I can select one or more photo's in a photo album by clicking on it (the border turns blue), but when I click OK nothing happens (nothing inserted). _(Once I was able to get one photo in the text area, although I selected three photo's. I'm not able to reproduce that. Whatever I try it doesn't insert photo's.)_
2. When clicking on the 'Profile photo album' or 'Cover photo album' the page I'm on reloads.
3. I can't select a photo when the photo label or filename is covering the photo.

[Running Firefox 47 on Ubuntu Gnome 16.04 - Hubzilla version: 1.10+8f2106d]

**Comment by jeroenpraat** [comment]
I tested this again. And it is still a problem. Tested master, 1.12RC and dev. Same problem. One thing I noticed that new photo's in new photo albums work. In existing photo albums not. I also noticed that photo's in the root folder are not seen.

**Comment by anaqreon** [comment]
It's my code (originally at least), so I'll take a look.

**Comment by anaqreon** [comment]
I can only reproduce two of these problems:

1. If the link that appears when you hover over the thumbnail is too large, you cannot select the image.
2. The images in the root folder ("/") do not get listed even though the folder "/" appears in the list of albums.

1.12RC, Firefox 48.0

**Comment by anaqreon** [comment]
> I also noticed that photo's in the root folder are not seen.

I fixed this.

> One thing I noticed that new photo's in new photo albums work. In existing photo albums not.

I think I am seeing this same effect with the root album. I added an image today, and with the fix, I can see it in the root album thumbnails that are now generated, but I can only add the new image successfully. What's odd is that the new image is found when I query
`select * from attach where hash="blahblah"`
but the older images that are not embedded properly are not found in the `attach` table.

**Comment by anaqreon** [comment]
After some digging it looks like the structure of photo items in the `item` table have changed, so [I added an extra elseif statement to use a different field value for the photo link](https://github.com/redmatrix/hubzilla/pull/481/commits/125713e9385a485b9b9615c0f016e99954c9cfcf), and it seems to work for me now for all photos.

So it looks like we're down to just the problem of the photo name when hovering getting in the way...

**Comment by jeroenpraat** [comment]
Great @anaqreon! Thanks! Not one, but two problems remain:

1. the hover problem (sub-issue 3)
2. and the profile and cover photo album problem (sub-issue 2)

**Comment by jeroenpraat** [comment]
Sub-issue 2 is solved.
Sub-issue 3 not. This only occurs when you have a small photo with a long file name.
