### ISSUE TITLE
Remote authentication not working

### ISSUE THREAD

**Issue by bashrc** [redmatrix/hubzilla#52]
I've checked my intermediate SSL cert and that all looks ok, but I'm unable to remotely authenticate with other hubzillas, either automatically or manually.

I'm not sure whether this is intentional or whether something about my install is broken.

**Comment by git-marijus** [comment]
can't reproduce here...

**Comment by redmatrix** [comment]
accepting third party cookies and don't have privacy badger installed?

**Comment by bashrc** [comment]
I do have ublock installed, but it's disabled on the sites in question. One thing which may or may not have any connection is that I installed hubzilla with the same domain and username as the previous redmatrix install.

**Comment by bashrc** [comment]
Also tried in a different browser with no addons installed, but with the same result.

**Comment by redmatrix** [comment]
It's likely the re-install. Nobody has ever successfully reinstalled without buggering something, although we've tried to fix issues as they've come up. There are numerous issues and usually folks give up and re-install again rather than give us time to sort out the issue (and it is complex and requires some pretty intense debugging on both sides of the connection). You can attempt to fix this by finding the two hubloc records you have on your site with the same webbie and deleting the wrong one. Then 

% php include/notifier.php location {{your channel id}}

This will probably work for sites which have updated in the last week or two and will only leave the channel stuffed on sites that haven't updated. Or you can re-install again and change one of your nickname or domain name. Or you can look at the magic-auth "server side" in mod/post: post_init() and figure out how to check all possible matching hubloc records instead of the first one we find. I did this recently in another section - remove the "limit 1" on the hubloc query and change the processing into a loop; only returning a result once all records have been evaluated, (or success). That seems to be the only way out.

**Comment by redmatrix** [comment]
work in progress...

**Comment by redmatrix** [comment]
should be fixed

**Comment by bashrc** [comment]
I still seem to be having issues despite pulling again. So far I havn't yet had any conformation that anyone can see my posts, and magic auth seems still not to work when I visit other sites. Could this be some incompatability between hubzilla and redmatrix sites?

**Comment by redmatrix** [comment]
No I go between the two all the time. You will have to wait for the other site to update before the fix will work. You can use the /authtest utility to obtain logging information that would normally be stuck in the other site's logs. I have to use this quite often because if I ask somebody to tell me what's in their logs for an authentication transaction they often send me the entire logfile and it's never at the log level needed to get an answer. 

If you run authtest it's best to match it up with the code (/include/zot.php and /mod/post.php) to see where it messed up. What I suspect you'll see is a failure to find/register a suitable hubloc for your identity because the old one with that same webbie is in the way and it doesn't verify. Try this against one of my sites (zothub or macgirvin.com) and it *should* be successful. It's possible that it isn't because I don't have the ability to debug a magic auth sequence that originates from your site. All I can do is guess and hope I got the fix right.

**Comment by bashrc** [comment]
After trying macgirvin.com even if I manually attempt to remotely authenticate magic auth still doesn't work. This is with hubzilla reinstalled and with the previous redmatrix profile json file imported (so any ID numbers in the background should be identical).

**Comment by redmatrix** [comment]
.well-known/webfinger and .well-known/zot-info both return 404 not found on your site. This could be the problem - we can't lookup or verify anything.

**Comment by bashrc** [comment]
Should those be generated on install?

**Comment by redmatrix** [comment]
They are accessed via mod/_well-known.php - we had the same problem with Waitman a few days back and I believe it was a server config that blocked access to dot files.

**Comment by bashrc** [comment]
Ok, I'll check my config

**Comment by bashrc** [comment]
By removing the rule:

    location ^~ /.well-known/ {
        allow all;
    }

I can get zot-info to work, but webfinger just shows file not found.

**Comment by redmatrix** [comment]
I think that should fix magic-auth; let me know if it doesn't. webfinger isn't critical today and we are forced to block http access (https only) as required by the spec. It works from here using ssl access.

**Comment by bashrc** [comment]
Although zot-info does work it still looks like attempts to remotely authenticate on macgirvin.com still fail

**Comment by redmatrix** [comment]
If you're still around I cranked up the loglevel on macgirvin.com - give it another try. I'm going to bed, but I'll have a look at the logs in the morning.

**Comment by redmatrix** [comment]
You have no hubloc (location) data in the zot-info packet. These could be tricky to re-create. Here's a mysql statement that will provide a copy of the one I have for you over here. You might want to verify the hubloc_sitekey is the same, otherwise change it to whatever you have in config.system.pubkey

INSERT INTO `hubloc` (`hubloc_guid`, `hubloc_guid_sig`, `hubloc_hash`, `hubloc_addr`, `hubloc_network`, `hubloc_flags`, `hubloc_status`, `hubloc_url`, `hubloc_url_sig`, `hubloc_host`, `hubloc_callback`, `hubloc_connect`, `hubloc_sitekey`, `hubloc_updated`, `hubloc_connected`, `hubloc_primary`, `hubloc_orphancheck`, `hubloc_error`, `hubloc_deleted`) VALUES
('uL7YwDiI3Ds15SzbXrrzQby2UaOmCOhxpBZdn_7p6mm0-tE8VCj4ba1_CaQ5hNvQOJMteITKYRr5RuAHrvIj5Q', 'P6zeyHH0ry8f18K2OqtVwjqBQrLopTHPXFxAlVaOQAe1UuGlPy4ZIYrtfuSvI1Eidev4Y5kn_Ek9gaVfBBiAOnUN-9o1di_Ump1PnIEvpigl-BJgtOloe5DDCwngxyABzU3Cl3erFZV5chJkPUdrrMu9pu313Tuqt7gI32xDLB67bKxQ3OEQ931r1ph_1E935oIVkRQJqITYK_P944IKNnp34GcxMFme-8L9-nq335JxihoePHSouxjNGFFLneR8JbDYWYOUROnvzWkSl6qwDoOuIAN_lRoTOn_FvlskIFJDSBmTZ0jEMC4YgDnac1YGJVyDTuOLWM3X7QF7t6OP-TRyY9iB8cHJd3ynqRR3GTcTWXDoFGrXulU8QsjSshFs5VzWyMnbmNyH8I8GvRIIxhfuRIzH_Yy8qXZm8dJEwFBrAXivAjjWJsEw4BTdpOLbUx1ZzG47aPSsqvb1ea8lbW09dHI7VMIa9KSZ7mzBEcf1go_lHeuHdfLoEXfW8QRQIqppFiJWY7EV-hhYhej-jDhRd_q9D90ThXvXAY0XX_lgp2FKIDrgdUjH5__5zg4K-KAZMpADOwZuW3E4oNlLVfzJx1P5oWSU8nrA7S76Ka_9Ni-JTLF1hCuIcs8s3MLSzEF-1CqmLn2pPCBVixqzsWWrRE1FMVhhAZ-wk8giFEg', 'Hb3ZrL5PT1N7HMaKy_8iBGzfhjciPkEt-rjLKF1ndDlfumbxJoUREHHXaOtPLOkdFoA3hpLzWKp1c2wQ82XVVg', 'bashrc@apespace.org', 'zot', 1, 0, 'https://apespace.org', 'tjMQY_YI1IuLLqATjpSFl49ODxexvpKZ0djqQXPMFm7Aqs92R6ro_uRURuSG_0wJCaQIojBgFW1MAtSq5CG0a9RzXXtBrqlX62Q5vzIcSbgjUcdt2UncwYMbv_zk2DcjE8j1E_0Ftx7yS3dXPJOvgQY-rEKqYnKktQYWJBw5tjlCtyWLuGaENEaVf71CDNJf8YXn3uThlyTFom_6I9TB2oorl3IF1geAslH4MerAzHD12pChKZMime_FMhOk1XdrhmWAw6rQf5a-cw__UU5prTxx5hq96dYU757HS-mq06BwVwoRQqa-XozE2EFE4R_fPZjqAzB_Jw5oAHSD1L1zdjGKbIWYCVEAPy-HnnuUH9fVhr3FAbecRE4CsUOoUu0QxiizOJbLJk4ps0wQ-DnNQlHfh0_C7dh17T3OUucfTTtXcPiUxfk_iA3bcCrHbxhOcKZXLftNZsD7p1g43lFWtfnprRqrM8ySi-_OhNEKKeQCOabM25U_SZOnCKjPKP-CMTRB99hxus_UKxGKuz-p5mGPBQgnYfpZCDehjIdgFivQLKPA611ckOU5wJxYU6R30HiHaHBof4VXMz4oRcYc6_vwoTb2c2KaFR6RZ1HMa0p9HShtnM48LJx8XSF8egypGMdXQ2eB--zlMGbxnm6OpCo21Z7O6wGQnlK8-wN8tyw', 'apespace.org', 'https://apespace.org/post', '', '-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5hgLBrF3MZmtTpR2yKrl\n7Xw+030DlcAVu/43UOII9MYdm+PwIKp20qqExZJWag/JNgO74xXZsW8pz4IqbZF8\nb7zuLDbJzxDXvt9hy6xrq0l68x2t80IKS/c2ZiVin/qpbGRc6qodMzwbq8ELwFul\n4CjUqwSFrf9W6fWOHDonp74X3OsIwOzCmw1JUpKR6H7XeJ1vtGgn4Oo5G/Lx7THa\nKjZt/b8ciZL7FkIKcbFHV2G63GFSoE0B7EPRXNGSjT3BSXRU61fumxeJ9AGSgm/L\nfADZ4JjYe3dhLSXhw3MDWmT1xC4UTyajhV98vYxMQI/MJAMeUw49+zpTdcZSDE3L\nyoqMa+mAKWuOyhySHAL7cbRQArdFuJ9+yZfBVmDIT/69wBjqHT8rmBkyAA6SmoCX\noJi/hHcc4JCdIiWC2MovgV+/HnpO+s3xEYAEXZ3RJ81ESBCO34HwABpmALJoZM/C\nO7YIfZUMuWmwitSJY/EeTQx1SA1FQZkAfu+EmUj8uN5V6aInfmgY0YAsvKcHk50Y\nWKD9f0lc1TpQysfKPA9BWXHJPGUuXN23iBqNkyiNRe7MSwnTUdRI2QbTyjIutZhJ\nSmOrm7MUhRCEjixj6ny8uygQYRUSmtmXBwIZUJL+WHB5ONZIsAXRpM25LGmvoFik\njdWwQC8yGplnGII1aInBSOkCAwEAAQ==\n-----END PUBLIC KEY-----\n', '2015-04-30 21:13:07', '2015-09-22 07:28:27', 1, 0, 0, 0);

**Comment by bashrc** [comment]
At what point does the hubloc usually get created? If I reinstall would that be likely to fix it?

**Comment by redmatrix** [comment]
It gets created on channel creation. A reinstall would probably fix that issue, but I must keep repeating that nobody has ever successfully re-installed. It seems there is always something new that goes wrong, and we've been trying to catch them all for three years. We do keep catching more and the situation should be dramatically improved over even a week or two ago. You're welcome to try, but I have to issue that warning.

**Comment by bashrc** [comment]
Public key looks the same.

**Comment by bashrc** [comment]
If I search for that public key I get two rows returned. Maybe this has something to do with the previous profile export.

    select * from hubloc WHERE hubloc_sitekey='-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5hgLBrF3MZmtTpR2yKrl\n7Xw+030DlcAVu/43UOII9MYdm+PwIKp20qqExZJWag/JNgO74xXZsW8pz4IqbZF8\nb7zuLDbJzxDXvt9hy6xrq0l68x2t80IKS/c2ZiVin/qpbGRc6qodMzwbq8ELwFul\n4CjUqwSFrf9W6fWOHDonp74X3OsIwOzCmw1JUpKR6H7XeJ1vtGgn4Oo5G/Lx7THa\nKjZt/b8ciZL7FkIKcbFHV2G63GFSoE0B7EPRXNGSjT3BSXRU61fumxeJ9AGSgm/L\nfADZ4JjYe3dhLSXhw3MDWmT1xC4UTyajhV98vYxMQI/MJAMeUw49+zpTdcZSDE3L\nyoqMa+mAKWuOyhySHAL7cbRQArdFuJ9+yZfBVmDIT/69wBjqHT8rmBkyAA6SmoCX\noJi/hHcc4JCdIiWC2MovgV+/HnpO+s3xEYAEXZ3RJ81ESBCO34HwABpmALJoZM/C\nO7YIfZUMuWmwitSJY/EeTQx1SA1FQZkAfu+EmUj8uN5V6aInfmgY0YAsvKcHk50Y\nWKD9f0lc1TpQysfKPA9BWXHJPGUuXN23iBqNkyiNRe7MSwnTUdRI2QbTyjIutZhJ\nSmOrm7MUhRCEjixj6ny8uygQYRUSmtmXBwIZUJL+WHB5ONZIsAXRpM25LGmvoFik\njdWwQC8yGplnGII1aInBSOkCAwEAAQ==\n-----END PUBLIC KEY-----\n';

**Comment by redmatrix** [comment]
One of those is probably your system channel. Anyway, I now get a location record when doing a lookup so the data looks normal (as best as I can tell from comparing encoded strings). Is auth still failing? At this point the output of /authtest might be useful. Previously it was just choking because we didn't have and couldn't obtain the info we needed.

**Comment by bashrc** [comment]
If I run:

    /usr/bin/php mod/authtest.php

Nothing is returned. Maybe that's a good sign, but at macgirvin.com I still see the login menu rather than my profile icon, and so I assume that magic auth is failing.

**Comment by bashrc** [comment]
A check on mike@zothub.com

Local Setup returns: Array
(
[success] => 1
[url] => https://zothub.com/post/?f=&auth=bashrc%40apespace.org&sec=54b8e2ecd7e67d4eeba9ea0ecdea484645509e13161c46bddd20bf2bb2df4d43&dest=https%3A%2F%2Fzothub.com%2Fchannel%2Fmike&version=1
[message] => token 54b8e2ecd7e67d4eeba9ea0ecdea484645509e13161c46bddd20bf2bb2df4d43 created for channel 2 for url https://zothub.com


)
Remote site responded: Array
(
[success] =>
[message] => auth check packet created using sitekey -----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5hgLBrF3MZmtTpR2yKrl
7Xw+030DlcAVu/43UOII9MYdm+PwIKp20qqExZJWag/JNgO74xXZsW8pz4IqbZF8
b7zuLDbJzxDXvt9hy6xrq0l68x2t80IKS/c2ZiVin/qpbGRc6qodMzwbq8ELwFul
4CjUqwSFrf9W6fWOHDonp74X3OsIwOzCmw1JUpKR6H7XeJ1vtGgn4Oo5G/Lx7THa
KjZt/b8ciZL7FkIKcbFHV2G63GFSoE0B7EPRXNGSjT3BSXRU61fumxeJ9AGSgm/L
fADZ4JjYe3dhLSXhw3MDWmT1xC4UTyajhV98vYxMQI/MJAMeUw49+zpTdcZSDE3L
yoqMa+mAKWuOyhySHAL7cbRQArdFuJ9+yZfBVmDIT/69wBjqHT8rmBkyAA6SmoCX
oJi/hHcc4JCdIiWC2MovgV+/HnpO+s3xEYAEXZ3RJ81ESBCO34HwABpmALJoZM/C
O7YIfZUMuWmwitSJY/EeTQx1SA1FQZkAfu+EmUj8uN5V6aInfmgY0YAsvKcHk50Y
WKD9f0lc1TpQysfKPA9BWXHJPGUuXN23iBqNkyiNRe7MSwnTUdRI2QbTyjIutZhJ
SmOrm7MUhRCEjixj6ny8uygQYRUSmtmXBwIZUJL+WHB5ONZIsAXRpM25LGmvoFik
jdWwQC8yGplnGII1aInBSOkCAwEAAQ==
-----END PUBLIC KEY-----


packet contents: {"data":"qeSrZLA6jm1DvSGWXiwGLh074_wbGbyIKgCLgM_gryGvYoADdpMNtuEpS7YrbkoI3gk8xdcD-0yDkbjfNH4k_-kI2i-t0cWLyxcMofBJXusVdL6z9LsyKJ4y2C6SopODbbm3FtgwW8mLJScpdfCL0DYaZc0dGd2iNFCwPzSJ5XRLvvbwfVgZrL1qNv7zg-YFhCP7FT_4esPH-0hLNr1hyyQDAzqWptLFAUJyI47jNBpShEqypJwl2TuboeDH-6PStti5_hNYSororFL8_m1R6eM8S6JdvmCmEu83ikI50zqyoUcQiT_8j8kXBhjckCxjKL0DybQuIV_7r1oyrr0jAuAvlZ3Tu7SNor1xsMVCKtmeXYOMhXQ_IKAIWwQ8KsQ3biCDNApI4E_1b6wwFThe-CfB8pTaPais9NwqUMBQnCwP6dUQpDkqOFQQ-3n7OFKQ_1suoROAm1l_d9amk54dP6QPBPtGQ26CkRQRFpuPKmtB_hgP8BSgYqu_AK8ATFFtcBFl_v2RGy2AUI7-4WvawGTmi0BpzIwLeOGyhQEvQXp-2woqN7F4NqGW1aAbkTOT6XO7EPlOdD-byjgc0QTbHK6tb56-RQ7mluDFdE0sayjfIB_cSou6Q4jxhXA0Ux7qNLYxH8bnDU_xdUsKr4m1T7MJLT2uxfbDK0fz7szx0mZC42RdEBx9BKN44B7KPxy2ZKOv9lNSU67NOUU_LDZhoky7BdfEay8y8adHhHIk3FqlojHCHx2U4blmnCjcGYVcytHcoO-Fxoj_09k1WiAwvwoHdKzp5B3glvO5TeGxfcOkm7jXpm2dtHzLGRTP84jP7oJrUjbIexJy1xGti9AS1cX6TkX8hY5bxKhsdoEnUB6LwDGQEeh7SufWdQZKjKP3cG6MCJSZHqdXDppfEHG8nFwZFCKbNUdGgb2CVz2rUmF1V3z9o34x7V9IVi-Hjqz_zBBahz_eQTylFHDN0dGuZPbsgOxgTcpa16qA20b83TnCHz2VQ8F1IYiEezStTNNcWrBqwWyBnhtfGFbhhsQTquvZn7sHq4FFVDdWJFBa3JPUNSMc1cFP7ExBlrVpKeXw0_NTjkpOzXShKw-lViDBt3tywvM9xAbR9920CtwZ7gf0puGht7UFfuCzy9mOXTqxQkbHBEeyPVaDgshgud6v9vMyjajQPzO4tITIvpmifB1YBa6fI8veST3N3HUFVlCsGk-vBUJESoRpf6wYDIMvSNHyQWiVwrmW5R4fZrzdWBltZFECmsRJlL3JDYSuCGPZxKskU4rNbgyiKevbrZ923MM_C3gxVvVZmAx_zQqLFeBr_LS3ZvrIzNH6pRVviGODStYSF7N2Qv-fIKChQ6hWdFpVJATbKQ6uNKiqnKCjv6T-tFd322qSMqAoEOE_VlxuACMMxT7Lg_iaiHsI58EHGH9WOjBB1wgi2Y_Jn1A8n-YKviBvCpeyHZyLPGYRC1E1mp25D3aELLQ858lj0OzJ9dCITNUrGpHeOuuH0tb4Ko6Ln5-8RaLtvcYbvz1BlgWSlTAR2iLVwWkmAOlLP1MukX9pVQxW_ZV7nkJ9Bb785QI8iYXjW-1gdnxPRlwJb8D44EWHxDchUQYXl7ivuGZzKpcOXW7xWG5rWxIiKGjiAvbLHWl-5u3uyK310TOjxrXr40jNwxEZ5-GX6Uuks-xSIw-x-XBE0yovynH6eI1YRB53YI5bF-cdWxUmBoR2DROLL9jrWp6hmUbob5Vbxy2aNBklebOgiL7wS8dIU6t2OmQK1w3dZ6VUB3xb7AitDv2esQqROXMh3Gxo9LIYYLqC3H532jLSPY1tdnpn6kyxZ4BsNSdE6CAxanxgyB6KH1s_9RO8SKm-LMg7nMJYpDXGYqdvzLftEZkD78dih3bP4ukbhZUGdbxQiVHPns55BgH7ZsHtQn61_7CmrvASGbn5t-biIevapF-njZrwLvLB3oZjXBVi2hBuYBbUHAW1zN-B2DnXYiPHRiTkkMNbla2Z_dcn_x_WeLdR_HkiP4TTDJ8eZXd5Apgvj6makLND2MjoiuwXGgAYjc4UvwDk3EWm5-qeuh64Hy_R4SwCgzxZR1NKy_beEt4KXziKzxQ4mFI2nl-0tfMEC-8JENG-Ef2Pm2VvktyipLhJi-ipFXG5cSUJ2iJ51nbQjR28szTAg5qZCzXXJc-KG2ug8AW-ASIoP2Is6G-9nOj4i7isnpMro8nvyZKUDBrNaZ_rygb17gfPd_vS-EfLl10bA_dGRhUyCCkScDFfs5nB7otv3wcOgFrWRMtYk-nwUMFpVoe-VWc2poItkzFydxzYI6v2hPEtPhHq6gcuLqI6mKVpS9MUBV_Q4LW2ghVrTls0JFSHud5GJiOmhqhtCEKgJKs0iux3xXpBoK-DFXY7r4dWfuhJSQfAtS0m4a54PZXFOZAfSnotJ1qH4MHPQlZc948cHi50a9gRbIYEyzK3wKRzIiKxpR3nb_uzyqF0bK0hmKlUy3LCK2Jv3n5XdtDsQidXL1ZPHooNWT-mYxppbMIeUdvNg6rX_FIF4gFylvqytQgInOOovtH25lExPEINHiDI4UbGc08XPjWfz-rzCvmCuEz3Ono_eJPt4SioJGRyp7oCRAU7dph7L7Mv8fWclexStW6lTGSdg8pje5NVyknWj5jjzdSnk2UX1z_Uhs0kZzQAfriytOiqQcOKqPG34zXb7udbUDHcPVysV2XD_-X_J4MYsSrSXgNaDSXTGyweMgcXb33sFx5tdQEizGyZzuiVL61oESlNhR88TyXLKUwkWgb4npMODV-OG9TI5wlKpatiqVn1CRWPOKOHlu6nP0iKMQwarzqQtyuqgAEQL21LccIZwcTY7Dj8vgXHbAi9eYm66UbMHyxwDPDkYaBVlfGDsX2as7J7kdKLx7-d5dTg_9_ttK_sAct5qnxhlg1xkfPSMzmuM-b8qT-NpcPhiEhsm9RsXhf84Hak_LiwBvjxjlxFvndsGo1JLdnNsT4HgR6P2cKJQetpVQ0YH7o5RJeKtsAl6hZNa3dK5_dLZQoX1XVqPsE_CnD9-jqmdkedxJ5P_xcVAHJp7Vq9jnJA6B0MuUdVJ7SIFoxotXMSrX0MVma_JcxA3XIASn9H0Ik5yBy9Q248kiP_90SQGm63YHOkcn-T2w8Bm-iQ75yBrJg5YyVN7C4esd1kmHvoRBOPdHhi3_JypBc6WaYF8ydhx1YXTJhi2AVjVOuT9Kr0sdLKop9eWmKzicTHtlePWglZCJNm6vAwJhsc895JvxWb4t1nM9-_7t_Qjxj9_P9G2B9l7YwCjedaaJhlER2TvpDUUsArr-pbgeMnN4sqeTwJ7SqJBSaXdulkYZlebLGqnXjyZph83aIzUi74RlLAUrFLvG3UnHwVBRZtkEP4iS7y1ENPQCr6qFvpI6mUfq6HrqjrwUEW1sIZ57BX50PKTFk3q8BtC4nvPSp6_CdK7vnoHcSkPBn8STDK7tw-tO19QU11mRz51LeF2Aq4U-6efkGsJCF3g5fjxYWqXB4PZhMqJNf-mIetRaoWNcthOt05_ws2O-kIo02cGtp0rt2E2s6mtaOBf8irZ6aoFdSbeVoKQ240RhRFvS5GLgejqAuLzkr82WdnUkqc8Upt031589MveGQDlKWCTEBvJdAU0NnSb6xaH_owgYn6mp94HRnp2n9MSE999FK-duBbKzU2u_5adYRDB3JyvYMRzEPe9XPWNWpbQ1YBZrNNCpJsGKDnm2taGc0MV7HRcYwCf1Z5_WeHpBMPeGp2uaauiGCGq62rZuOuYMeGHpL18geQQtZb1GvUD2g-BvMhcwomymCFiOCpJZizm24lO1hdlLCnmtrHrWaKTlagZuWiYFST8zPbHJCeiS0h1aJoK1NF29KO_hN1dBy2BVO6PlkPaMtGPKObQBXYM-Dk1y6HE2V498jeMwFRLGhork5Pg5RszfooepnyczW9SOeRmVMsxtdhIxDFcjFNwPBS5pPwNJHSdZDJewgy7AI7tQMVqmyGnj4iyZN3q5uQ7fymcP98CdpYR6HXHkHRNoyUZOnzY-b78Aer4PnJJej1c2YWrk3q7WzvkWuSOjg83R2Ov0TH010fVBjQE-kRK_Ayfmxpp1uRddBi79pgcopYTXoIBABSu9qZZCh8ONU_KVbWklNolErpv7HEe_39PXSvlCSP034hKL1VWQtymtUe_dLVaKVcVyHZpS5HSbMcYpFv","alg":"aes256cbc","key":"bjYyGLCY7trR0qU9PnASPTQ63iKKkUrQOl7QDHdfo25p9AcQ4K6G6cawrThJlDy-Ybwtkq494flm2kLHYevnQkUTjNc0mBTTd5vPLsIy2fHhxXUplH1U4vU6KF_j-3jk3sWG3qImCZveBT8xSpeouk7N7wty68SvDiUn9JMU8h9JzFwJ5SIF57kkLpor2TDJmAA5V1nkkYTehHM9eNnCFCNwap9nqvpvlHBgfYqb7_tz6fwRu29cyyztGWLoqapC_f7H-N3gZ-pC-Gi3HQLwaZhNg8jqF74t6oC66sX8h-yHrGYGsxYpBVRE3v8Hjw06G14g8a5dT1xAx9SvwitpNoJM0utJWX0eG5YxtxemzoiwYo-XjHM2MEJNxh3sAS8bxCeSvQV2yAwnJzCK-Rlv5Ty4HjQ3pn-M8JaYvxyFXGeqQbdNbsEzd0pnVVDXJwMqfY6MRI5c5dpxWKlTOCDw2VLQ44j94gQNGfQ6oj6RyiZys2OzlrbPLhEX0EDTT6PjbL6kdRQaDG3AMf1DZWBw04r9Ryyc7KtJwwQyV4N8K1rij2gucKJQfDW98Uk0ZDnWZfpeyMAJTFbTh1-jrSJ6SAuM3QntV9M-LQ2xU8PXdAgZPhn5Ev91ALXFfmFltT_Sp49ihDdZQgO5XcUbwaiL4Qg2DrVo8CTyownp2sBGEOE","iv":"pjimZ9uiwRxnAsXknXx1IAu-fKScp-abZy7elqQkGBhmS6e1juHAXlb6nPlTVY3pBQQn77gAJi98O6yJWqdC_TdaQxQozkNMg-ipgKVA4KGAaAKQ1UqI9jlzjvz17aDO8sHGmpOx2sfCe2GJX-yd0sK3NFTzB1Hli4Kuv3FcXBZ2bMGfQGYIORIxI_Oy-AxVEmUPkB-Tf2QtoUtdcmSHqfxaaxkjyb1ymZOuQLV2IyRFV-nOtpx28Cy8ZNUK1Qr8eaAxUkXibuamHksjCXhs0dzphxuNbTUdiLbBxxIIOGMstrA3-2Mo4d0xZpNw9dSOQ38ABJ3lzLlyYU4FJH85dXlKzpLBc4jcHYprpKY6Z0uueWPZtP96WNpz19uUDn4Wtz_VrBUn9vJYfrKQaQehKCi-DeaeG014mrSO74mhcqV-XoiuL7YxeKg0KrAxnueEXgtqXvRld9n0r-sJFnDiqFIwLeXATW9YJV_402DxurRoJeMKL1KkLJlD8V3KbJK1uMZL8oRt9NfUbZodjLsF0aTMoAgY8pGm6w5vBYAWGKxo3jfYjsAsM8E-2kNnpso8_DSwrjtdMpzhtp0EK20R_LhG-_A0P_0x3XDI82SoHydo2EdOQ2-nM60xE_4NakjGpp_gSfosmNyysq_mgthgx8jJJJhX_OSNwQOvACL0PnM"}

auth check request returned .Array
(
[success] =>
[message] => Hub not available.
)


auth failure. Array
(
[q] => post/
[f] =>
[auth] => bashrc@apespace.org
[sec] => 54b8e2ecd7e67d4eeba9ea0ecdea484645509e13161c46bddd20bf2bb2df4d43
[dest] => https://zothub.com/channel/mike
[version] => 1
[test] => 1
)
Array
(
[success] =>
[message] => Hub not available.
)



)
Authentication Failed!

**Comment by bashrc** [comment]
A check on trouble@macgirvin.com

Local Setup returns: Array
(
[success] => 1
[url] => https://macgirvin.com/post/?f=&auth=bashrc%40apespace.org&sec=803687c11dd1a8eff0a3e6bbd6bb58c05fe5800e4e3666522039bf861d6105a5&dest=https%3A%2F%2Fmacgirvin.com%2Fchannel%2Ftrouble&version=1
[message] => token 803687c11dd1a8eff0a3e6bbd6bb58c05fe5800e4e3666522039bf861d6105a5 created for channel 2 for url https://macgirvin.com


)
Remote site responded: Array
(
[success] =>
[message] => auth check packet created using sitekey -----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5hgLBrF3MZmtTpR2yKrl
7Xw+030DlcAVu/43UOII9MYdm+PwIKp20qqExZJWag/JNgO74xXZsW8pz4IqbZF8
b7zuLDbJzxDXvt9hy6xrq0l68x2t80IKS/c2ZiVin/qpbGRc6qodMzwbq8ELwFul
4CjUqwSFrf9W6fWOHDonp74X3OsIwOzCmw1JUpKR6H7XeJ1vtGgn4Oo5G/Lx7THa
KjZt/b8ciZL7FkIKcbFHV2G63GFSoE0B7EPRXNGSjT3BSXRU61fumxeJ9AGSgm/L
fADZ4JjYe3dhLSXhw3MDWmT1xC4UTyajhV98vYxMQI/MJAMeUw49+zpTdcZSDE3L
yoqMa+mAKWuOyhySHAL7cbRQArdFuJ9+yZfBVmDIT/69wBjqHT8rmBkyAA6SmoCX
oJi/hHcc4JCdIiWC2MovgV+/HnpO+s3xEYAEXZ3RJ81ESBCO34HwABpmALJoZM/C
O7YIfZUMuWmwitSJY/EeTQx1SA1FQZkAfu+EmUj8uN5V6aInfmgY0YAsvKcHk50Y
WKD9f0lc1TpQysfKPA9BWXHJPGUuXN23iBqNkyiNRe7MSwnTUdRI2QbTyjIutZhJ
SmOrm7MUhRCEjixj6ny8uygQYRUSmtmXBwIZUJL+WHB5ONZIsAXRpM25LGmvoFik
jdWwQC8yGplnGII1aInBSOkCAwEAAQ==
-----END PUBLIC KEY-----


packet contents: {"data":"a1uEhD_Nb2__TuD8WA3Ucf6rxlhUlghkTRyywGlYraxCyOA6wdQVhJhfef4hITNRfqY6jsUwukpNs1MbOG30Ccn4DwIlrnFhQD_MjQFpbzJaRcOKmJchnz_8e3IhCfnmKuhedhEpwhadxXLdOBYT-4zkxmBDvIGTTraZDtm62e8VnmlvX0TjeBuvSVWcmBi6L5FLOICfAwv3UIM0Gi4WxYUoKzGipsy82qTr5fBEBaL92tmnsFaQ2Fz_sMxeDFuc0UX2a4JxoXCeY0jU5B1m-Mzxj2daBtjPNZLwHA-nj9iD48EZptBPoxuPRfDgbuTXcblfm_VxA3lH07MDAjYrf4rx40sulgP-osRJM9J2sW_m6QOULEhLCp9YzZB01094mfvyrQd-SlvDeuYyXchgNFCS3PgG8pIBR5L3cUQ-ueFFYgKZYees6NJNTCkUl753KL5kEcIzlhAoDQd0rcoVhgh6RF668tStl9Nk0arCb4Hj94gG_TlCKBerFindhnlbj9zeSaXRjxRatASy5HzwMPQO_e7ledw1BJfcN87FqREfcmjFOj4ThP6a9P9kAeZqDlZk8Dl80uDQYska3VQfiJ_Igx59vBMKJ2B4DTXHdm6ZkZNEgTkCerMJObPh8Qr-VWr5h7Oakvwp4g2zuLJtKFUFV5hNUBomyVPt3plL0_AFTWcLU43Gsg3gR6YoBCW31zZH6xvb-oybkoajxmWeLZha4df3QJNnR8SUeD7fYvBzG-nVttH1AsL1Cit0edVjjoP21-L01pc5vZDqMnr1WfR4YY5GbH-1wF3MMIkGq305fQgKdI0Yty56OTtx8bOkcpszqk6_LqFKzsRbdFVtQ-7cvNGIdKZ2XcJTPt1CnZlSjANgKT-ZYvZrLvUBl15Lb7yabdVLNvXuX6Q7Z0Al_K0448j2FIKQI9SsnUEYbRTXmv3KcvCY4mh9C8Nv7HsPUGlFPjjCmO1-QAj735FgW6ZvopM69iAyx2VzvWQ2q5yP0uDeOoKoy5mvyPQ4DeSO1MI6yO1oplzAmwHhwqiTpqqkt7Fz501tz5QoX1XCzFoAje8A5M9TYmeVaZ7L54K3nc5IUiLHHs60znTqu6Gr8A-lvrLnV-TbSowjo93hzkjs72q1RIc2VbUpSe1NvSFnfklz-bGfsCcxcpWxoUyziD3QFmKEYYrlbddGai1Em06LsWLn6DQFRa0_EOosUeUB8Vj-PCqZP9kLZGRnaHALP_fTlA_Br6KTIAG8gnOrTs4cBL3R_1lNeBk8jXkNTHmpnTY-BabeBPBEwDvSw32nFTeOBjvAb_tVnzR2LGH9glVUMvxDGDBc3xsjcLqM2TCovM8f1puNUJoHp0YM5l9xZ2AMnJN5bLhaAyizqpFcFG1kXPlZyYwjyfbCGEVguHbzdkqoCajrmTqu301AUGMbPbBbevmO7VJWXbVukNofx-z0Sxg-5vfJdeIIAjLJRDcKjvprHjCJaaTEwkjN1ORdlENGPQsi8RCRGuva-ufPoB32cWD1UviNO8EcDYCgR5Z2HgLCCjsP1BVNY5mL9ykDt27Lh26GxBAB1-xT8RhZnX2N0EkFBek31qG6nE1e9QXleFhhi_4pkmy-rPgdUFnqOpzSMZnJGxoiqhL7HFXCS5OmZxGcgO-HtAYkUzF72-85Be3fKpIAgZ1jz4WTA3Q7g0zVkEKqyk60-dbyzpJkOsWxQEMgmpy5BZzPlrE-3HSi40Gn5OlzOs7kLoewpiBZzvbSoV-pPQGogMl23Jl8_aJu9T2Dwhcu8fUXsmsAYs3UYV0R3_37QXgH3iNYTxJ-F5_CSCGzBnEFBvjloEnzU3XjoB90fCLfKJ3KO6UCVdr1fqSwU9nJcl7-xuqkNseomsQOJheMEBykFN6TbPezpmU_TMN1hC7SXOUB8VOl7fwL6nhBfkuwayML8DmRZ1sQd6W1p_oDU550-DZgdHJhOkEQNlK-63sREqN2IXHvT_ArAYB4AXTY99zAAe4CgoevUKIj0_7i_HIIVKDgQ9VYnXYznN9-Wysj_gINfoectjNtd8glYWVwlSJC3ifXRlOGxIFmqNxmWM0DX9LXTaEvsGt35fSuIMmtr9fCwIgjyibdr64J7QiCk5ipWyUO90foCjhROPwx3Ao4KzsdikSbAU1Oez1IflZcv1D3vqtMX1fMVaJLdCP7QXYEFUMGqrX7w6z-1lHU0EGXYnF8noSCuadb3VkOiyAoY27NsPa4bwv7ArMSqOAKB4H2etRn42xz5Q9PWfRGZnFdkLP_rgiQ6dWKkl5gIX9lmo2JmrfyTEmQIkIhKVD0sXq8g4gHvyGDVmk3i59uc3tKy8-rQdggCoee0TAsEj7DP-9iE6obfdGbOiwLoluCeK3o_BqhPv6eFwbGMIfvO1fSPg6QjqyJFTs3dPuFDSEULPFGv_r6x2qbE10VlT_GcttrI03nGLFmaLIBlut5FEpSuNApF3dEVUHc17GYwq8jxJXoKFj-UfFJkDE7wLEBzMsomCyMri_uGyYUbE77SN3VOnRLSEjQ51ugj5skRNgVB0OL3SOO2v6PRZbJmMqpdR-TZSqWM16-fvfR__sDQBBlCCoi0AVtUtoDbkKWMxgxZoHJ35Ejq0t87BjUsKW4KV9nhJqMTc46GdHlvOmNReKi_sVCxhw7cl5OgvGk064rSG5g5NFj-7QUtxXmDEMz_FEvcmSdPqkS2juPhRyb0CS9RHJF7VgwpYbq5WmxXRBk33DuQZwE2WkQbrNqA8TrBwj0AASbch2vHpJ5bG9YCWhEveSjRUgSjsgHck8MeoBjNJli_1Od-n9hM2-llm9QUkGV_w8okUT_hBi1kXmvJBOJr6sM2nT7rYRbFwiO_Hp2YmRiXWuOMmwhK2Sh42Wc2RaMfK2QmlqRaEUuR49u3oqSx8I42-RpNhLA6CrtB-18YjheFFgowjtRkvNDpEN4S2_9JBuC15LMXYb32KULs75uv36tCT-3RNMtevILsTEAmtP6P4emQZGDHOqbW2emcVLSXzeiJ1Mriv5BopvYsvl8s1qdpoakRQlxZqhdixjO5iLkp9WWplXtPIgtE7qmQQIiJc4piOfcjFH8qKtRXYLx2N1EImJesVdK1qPt2JDNyi9_X59op29uZ5A6nIA283JHfnCv4vKplh5ev70hNnTbqCZjuN017bQWj59KgC4vViN9SJpzDdZ1qJER_mOX8Kyitacocbml9TVoGH63PMuZquSDGK5JldstdYx7GXKEAZ4rTZPLZdKic_fpbBw08UM9vPOojMB3n9w2jSN-G6lDXPsge0nwCVHqPcbKeZfE8YfALkYADV_hHzdPBnIcHSXUtTcrB21DXgfnT9fB8sSv4K4MlpnnGG509k0ULCfCIYVveF46R7Tmz6R68KSR-TNhwCkTK7OQL_Y3HLu99B0OvqmNAFXGJs04Es7IZ06PXKibwtRxDYkMljI5bML72K40cmkn9p-Jtu6uXHFETk92jxYPWGz7X5POJ63As0xqbFmt2jmygnjvCct36xovafPmCiHyyfAcH7ZDT5B9T3u11_hOngX0x2U2jbV6Szn1QMeBxNEQ6DCNFUk8Ff0JBTp2v1gAKEaPGDqoHFOyO2uX_7HjlNAPfQmAeWLY6kP8jpVm4diAcS1z4gyz9ZCY8sZBBJfiMTjhk3g04aDQB-22IoV4Fq2PESJIcaMdOf2KR_T9o58aQz3x4XTB_AFqfue8hXQ_ozO8KUxTt7FYw4K06Ahw0Yd29DLDSDmg6u8eajqkmj_vJr9DXNwGkMYvLwG3quZ6Az_NldP_KVEtPOQd3V8_U0JjbyQ-qqiPy2NrSMl275p74bDDbe7cnkO8EriXdQUkEpUQjgrRmkO99i9G_Ckh3nj069yyUeC9z3_087D-DzIkt_OVqZwYUshIyPuzwyRFkv3j3UU_pa5k_a68-dN60slFHVXml41no80PhNLPOzNrPH9C53kU9wpOkXe5esz30AUxSmFl51w0P5Un7pGDR90VznU2vlcpS5nQlB2mu3baxldvU5R4YhSffpkcQS0Dj_o3_fEeMa8esLeoAnRtDPvpcEx_Cj56M9BH1KrlhfmaBPOVmh1JSwiqJstlsenF6YmiRiDYQ2ZaOGa60HCbP9n8l58uNw6dNP8oa9Nix2DFm55XwPqReHHPwC0X9yovvAn1Zbo9AldC9xj3f6ZduuZofivAwvJKf08J2SY7itIbeQrFOWuht5_wuOT5AmYNxekJNA","alg":"aes256cbc","key":"KoMVO1YT0Ry2wZLCLIspMuJwONmvHoWcVKKTt4-Gq01FZinHli42lXpnx_OtNoxll0---4CCNTihzebfwcGiwHC9x0x6oDMt-0azojp2mIam_e6SYZS7T0rRm6gW39vONycMi1HyJe92efwp_9IIHL1ervcbWmNqd_McVVTPl9OnALuBbCX0VqcXUzorsolvSfRFZQ6Ywq1kj8pH46IQ5W2Nm_weTn8U_7eY_MXVUkzTllkQQ5qJtzfx7IP_hrphSPN2H9CtG7x6gJKFCAFYMv5KRUEzgTyNEfpmBOOeqsF9xQEHA_cf3bc41v4OAYuA0eIIsSvQ4mFbz3LI4lkjwZDis-DYg8Gx-9hj9Y-YKPwgnK2c0RTZ_yXDidePKwD0Lijr51JDnGdFqFDGhJ0xCEhY9G5uPG0tOTvifq6wgdJLLDKp6JqULerNOfQatymp6sqTszW6nRztA522MKRso53vppz9S8PBh4o0DiZ-mhgZRXMYJnx9FCi5b55SX44zdupcJn4tVAxQyEAe0Pl11v15rsYGhxcHX6IW-klcqVsHb0jcnl1c92lh75qGWmoKdDF5ARvC9L0oETXtLW-lZDVRX7Na8nnN90HhExLMxAEWec-PbdY3rivhDhXQV1uK1afkN2hwEB-54ZCtMR4kdou4BMMaKCfMFYHzphbDVNc","iv":"OJsH7wDMHHgEwwgOf6gBpPIOJ6QOEhU0thzN3ydFg8z557ThO-C1d6B_dM7tALb-ZSRjUdJjpOP845kRURMLWfNrebrCdaMek7xJ1DZ4TcbXT8KrNCpEWmYkM5J2Z--v6FHWS2fuKurIBJGIQFidroyhx_LI1yhWpXNkYxZl7N4J-uE3LPByvkJLmNVeCpZuvjLQ5h0yLBGywC2dtunxKdNF8rIyqI2MwqS6EZTXzBNsFrYClZEbprau_gOu1j3OWuSSKTdh8xTFmDXm8zQOU4tQH37UyvxbZY0LxNRnWvenvgGjPuvSy92KErxB0obkIjQHo62MUZrHqCdpYeT3uxKHzvE9kjkNbLxjzM80Z7jYn_hZwY_1L_SzVDIM_oO_wzouqkiSi3D7nzmBmtEqNnoyiCGGIA3hiNpsacLUHyzxChOrUS-21H71lh4pvGYuU7ArfaU5rI7pImAw2HNAsRx2xLuJiByr_auJRJBht-UulFuiS-1S_6cc2iWcO_BHACaNRqt_7qJwdNZBydMjouBXvYBangyVZzsPxYIeYLHXEnU6X_1lFuwCGrdvOs-w8my68Fj0Le4c5mNyZ5TqfnhwY5I9RydLyg7-LYOcor8pyA4ZGtAKityYX4CKVmu2lxNK_7AseJjVjj9sPTqXuyFmeeKULCy-rghLXRRySwE"}

auth check request returned .Array
(
[success] =>
[message] => Hub not available.
)


auth failure. Array
(
[q] => post/
[f] =>
[auth] => bashrc@apespace.org
[sec] => 803687c11dd1a8eff0a3e6bbd6bb58c05fe5800e4e3666522039bf861d6105a5
[dest] => https://macgirvin.com/channel/trouble
[version] => 1
[test] => 1
)
Array
(
[success] =>
[message] => Hub not available.
)



)
Authentication Failed!

**Comment by jeroenpraat** [comment]
@bashrc Is this still an issue? If so, please close this issue.

**Comment by bashrc** [comment]
I created a new channel. I still have the old channel and so in principle could try to debug this, but it's probably not worth the added confusion.

**Comment by redmatrix** [comment]
Should have been resolved in 5dade2b608a . If it is seen again we'll open a new issue.
