### ISSUE TITLE
update to hubzilla 2.4 --> all links of all users to photo albums don't work

### ISSUE THREAD

**Issue by lazyadmin111** [redmatrix/hubzilla#827]
Hey there,

I recently updated from hubzilla 2.2 to 2.4. Since then the links to albums in my channel posts don't lead to the corresponding album again, if you click on them now you just get to "recent photos". I checked if this is only the case for my own installation, tried out random hubzilla channels, and found now out that this is also the case for other installations. It seems to be a bug matching all hubzilla 2.4 installation and all links to albums.

I am not sure yet if this only meets for links to albums which were generated before switching to 2.2., but I suspect the links are also wrong if you e.g. like a photo which wasn't liked before such that automatically an corresponding post is generated "... X published Photo Y in album Z". Then the link "Z" won't lead to the album.

It seems to be that someonen changed the album ID format, in hubzilla the corresponding number string was much longer, now it is at least 2x as long.

My first question now is: shall I switch back to hubzilla 2.2. and possible loose some posts of the last few days, and then switch back to 2.4.1 or can this problem be fixed without switching back and forth?

thanks a lot for the great work
cheers

**Comment by git-marijus** [comment]
Switching versions won't fix anything. We do not support downgrading. There was a bug in 2.4 regarding album links which has been fixed a day ir two ago. Make sure you have the most recent version.

**Comment by lazyadmin111** [comment]
Hey again,

thanks for your hint with the new version. I updated it now to the newest version, however this didn't solve the problem, the adlbum links don't lead to the album but to "recent photos".

if I put the mouse over an album in the photo section, those have an link looking sth. like that ... MYCHANNEL/album/95d8efc5ac8c8f25ca909fdaf74c0c4e3acc76c9603aac3aa0a7c4c74bbd0955

however in the blogs of my use, the links to album look like that:

https://SERVER/MYCHANNEL/album/323031372d3034?zid=....

so the IDs of the album were generated newly and the links in the channel now lead to nowhere... :-(

**Comment by git-marijus** [comment]
The album paths have changed since 2.4 i will look if there is an easy way to keep it backwards compatible with the old paths.

**Comment by git-marijus** [comment]
> the IDs of the album were generated newly and the links in the channel now lead to nowhere

It should work now with new photos.

**Comment by lazyadmin111** [comment]
So new albums will auto-generate now a post (unhide) with a link which is also correct?

What about the old ones? -- you think you can find a fix for that?

**Comment by git-marijus** [comment]
> So new albums will auto-generate now a post (unhide) with a link which is also correct?

Hopefully

> What about the old ones? -- you think you can find a fix for that?

As i said before... I will have a look if there is a possibility.

**Comment by lazyadmin111** [comment]
ok...

**Comment by lazyadmin111** [comment]
PS: the new generation doesn't work neither. The generated link has a bigger length, but is the ID is wrong too.

**Comment by git-marijus** [comment]
This should be fixed as far as it is possible to fix. Closing.
