### ISSUE TITLE
Remote authentication stopped working on most sites

### ISSUE THREAD

**Issue by Cam-B** [redmatrix/hubzilla#953]
Hello.

My Hubzilla address is camron@hubzilla.odat.xyz

I've been having a strange problem with my hub all day now. Remote authentication is not working on most sites since this morning. It's still working on some like:
https://gerzilla.de
https://hubzilla.zottel.net

but I can't login to most sites for example:
https://gravizot.de
https://hub.digio.space
https://hub.libranet.de
https://ioh.hfrc.de
https://start.hubzilla.org

I did a fresh install of Hubzilla 3 this morning. I believe authentication was working.  A few hours later I came back to find some connections and noticed this login problem.

A copy of my log file is here: https://www.eternum.io/ipfs/QmPuade2mxMowoRnoifTCXTdzfhBoT2rFPp6uno5sdmFft/

The main repeating error I can see is this:
`
SQLSTATE[HY000]: General error: 1364 Field 'xlink_sig' doesn't have a default value `

but I don't know if that has anything to do with it. 

Is this familiar to anyone? What can I look into for fixing this?

**Comment by elvecio** [comment]
'familiar to anyone'
yes, but for what I know is (was ?) a problem between -new vs old-  hz version.

**Comment by Cam-B** [comment]
I just pulled from git today and my admin panel shows Version  3.0 - 1198 and I'm guessing Gravizot is also on the most updated version.

**Comment by zotlabs** [comment]
The sql issue is unrelated and i fixed that. I highly suspect it is related to either being a new install and/or  re-install. Communications generally works during either of these events but auth happens inline and if we get somethin unexpected we defer it to background processing. Reinstalls are very messy and make take a day to refresh across the network. There may still be a bug, but I'd give this 24 hours before worrying about it. Let us know if it stays broken.

**Comment by zotlabs** [comment]
[red 468e976] OpenWebAuth: can fail after site re-installs; this may need to be pushed forward to hubzilla/master

**Comment by Cam-B** [comment]
Yes, sadly the issue has not fixed itself after about 30 hours now. 

At 10:11 PM I tried to login to https://macgirvin.com/channel/mike&f=&owt=?f=&jsdisabled=0
Maybe you can see some related errors there. 

Since trying to reconnect to Gravizot this morning the Support feed is also not syncing on my hub anymore. 

Is there anything I can do for now?

**Comment by git-marijus** [comment]
The potential fix is now in master branch.

**Comment by zotlabs** [comment]
You can test again against my site (macgirvin.com) as I've installed the fix. Assuming it tests sucessfully, it will need to be installed on any site you wish to authenticate against; which unfortunately may take some time to deploy.

**Comment by elvecio** [comment]
@Cam-B in /directory now we have a lot of _you_. How is it better to act in this case?

**Comment by zotlabs** [comment]
> in /directory now we have a lot of *you*. How is it better to act in this case?

Dead identities from any previous site installations should vanish from the directory over time as they fail to prove they are still alive. On the short term there could be a bit of confusion.

**Comment by Cam-B** [comment]
I have tried throughout the day many times from 2 different devices but the problem remains the same. Just for the record I tried at 5:46 PM to authenticate at macgirvin.com but it still fails. 

I also updated to the latest version on my hub with "git pull" 2 hours ago. 

My hub is also not syncing with the Gravizot support forum since I tried to reconnect after deleting the connection this morning.  

Would an install on a new subdomain be the cleanest fix for now? 

@elvecio 

> in /directory now we have a lot of you

Yes sorry. After my fresh installs I still see the old Id's in my local directory, but I don't know how to delete them. I'm already using a new database and new files. I don't understand how they are still showing up in my local directory. camron@hubzilla.odat.xyz is the only ID that I have control over and backups for now.

**Comment by zotlabs** [comment]
Should work on my site now. I tested with a re-installed channel and found another little problem which was preventing the previous fix from behaving correctly. 

> I don't understand how they are still showing up in my local directory.

Unless your site is a directory server, the local directory is still being served by the remote directory server. It is just filtering the results appropriately. The orphaned channels will vanish over time.

**Comment by Cam-B** [comment]
Yes it works on your site now :+1:  Awesome
![screenshot from 2018-01-13 18-36-54](https://user-images.githubusercontent.com/31628918/34911121-1c9e261a-f891-11e7-9575-0164c54cce6a.png)

Thank you very much for the quick fix! :)

Since waiting for others to deploy this update will take a while, what do you recommend I do until then?
I cloned my channel to a different hub (https://hub.libranet.de/) but that doesn't seem to help.

**Comment by zotlabs** [comment]
I'm recommending a 3.01 hotfix release. We'll do what we can. First we need to wait for the fix to land in the Hubzilla repository.

**Comment by Cam-B** [comment]
Thank you I'll be patient. Can't wait to clog the Gravizot forum with more questions :) 
Hubzilla is wonderful software. I love the nomadic identities.

**Comment by git-marijus** [comment]
This is fixed in version 3.0.1
